dist: trusty
sudo: false

language: go
go:
  - 1.11.x
  - tip

services:
  - memcached
  - redis-server

addons:
  apt:
    packages:
      - graphicsmagick

install: go get -v -d -t ./...

script:
  - make build
  - make test
  - make lint
